version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: docker/app/Dockerfile
        container_name: aylo.test.app
        restart: unless-stopped
        ports:
            - "9000"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - aylo.test

    db:
        image: mysql:8.0
        container_name: aylo.test.db
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks:
            - aylo.test

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        container_name: aylo.test.phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8888:80"
        depends_on:
            - db
        networks:
            - aylo.test

    nginx:
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8099:80"
        links:
            - app
        networks:
            - aylo.test
networks:
     aylo.test:
        driver: bridge
